name: Unit-Test-Build project

on: [push, pull_request]
jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }} 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - Android # Build an Android .apk standalone app.
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set Up Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2021.3.11f1
      
      - name: Build APK
        run: |
          unity-editor -projectPath . -buildTarget Android -executeMethod BuildScript.PerformBuild
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
